update_fastlane

default_platform(:android)

platform :android do

  lane :bump do
    Dir.chdir("../..")
    sh("perl","-i","-pe","s/(version:\\s+\\d+\\.\\d+\\.)(\\d+)(\\+)(\\d+)$/$1.($2+1).$3.($4+1)/e", "pubspec.yaml")
    Dir.chdir("android/fastlane")
  end

  desc "Deploy a new version to the Google Play"
  lane :prod do
     bump
     sh("flutter","build","appbundle","--dart-define-from-file=assets/config.json")

     upload_to_play_store(
        track: 'production',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
      )
  end

  desc "Deploy a new version to the beta test track of Google Play"
  lane :internal do
     bump
     sh("flutter","build","appbundle","--dart-define-from-file=assets/config.json")

     upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
      )
  end
end
