update_fastlane

default_platform(:ios)

platform :ios do

  lane :bump do
      Dir.chdir("../..")
      sh("perl","-i","-pe","s/(version:\\s+\\d+\\.\\d+\\.)(\\d+)(\\+)(\\d+)$/$1.($2+1).$3.($4+1)/e", "pubspec.yaml")
      Dir.chdir("ios/fastlane")
  end

  desc "Push a new release build to the App Store"
  lane :prod do
    bump
    sh("flutter","build","ipa","--dart-define-from-file=assets/config.json")
    upload_to_app_store(ipa: "../build/ios/ipa/flutterfast_offlineApp.ipa",
      submit_for_review: true,
      automatic_release: true,
      submission_information: {
      "export_compliance_uses_encryption": false,
       "add_id_info_uses_idfa": false}
    )
  end

  desc "Push a new build to the Testflight"
  lane :beta do
      bump
      sh("flutter","build","ipa","--build-number","--dart-define-from-file=assets/config.json")
      upload_to_testflight(ipa: "../build/ios/ipa/flutterfast_offlineApp.ipa")
  end

    #* Shorebird *#
    desc "Push a new release build to the App Store using Shorebird"
    lane :prod_shorebird do
      bump
      Dir.chdir("..") do
        Dir.chdir("..") do
          sh("shorebird","release", "ios-alpha","--force","--","--dart-define-from-file=assets/config.json")
        end
      end
      upload_to_app_store(ipa: "../build/ios/ipa/flutterfast_offlineApp.ipa",
        submit_for_review: true,
        automatic_release: true,
        submission_information: {
        "export_compliance_uses_encryption": false,
         "add_id_info_uses_idfa": false}
      )
    end

    desc "Push a new build to the Testflight using Shorebird"
    lane :beta_shorebird do
          bump
          sh("shorebird","release", "ios-alpha", "--flavor=staging", "--force", "--", "--dart-define-from-file=assets/staging_config.json","--export-options-plist=ios/fastlane/export_options/export_options_staging.plist")
          upload_to_testflight(ipa: "../build/ios/ipa/flutterfast_offlineApp.ipa")
    end
     #* Shorebird *#
end